sudo: true
branches:
  only:
  - master
  - develop
language: haskell
git:
  depth: 5
cache:
  directories:
  - $HOME/.ghc
  # - $HOME/.cabal
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
matrix:
  fast_finish: true
  include:
  - ghc: 8.4.3
    env: GHCVER='8.4.3' STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml" BINDIR="$TRAVIS_BUILD_DIR/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/bin" OS="linux" ARCH="x86_64"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev
  # - env: BUILD=stack ARGS="--resolver lts-12.12" STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml" BINDIR="$TRAVIS_BUILD_DIR/.stack-work/install/x86_64-osx/lts-12.12/8.4.3/bin" OS="osx" ARCH="x86_64"
  #   compiler: ": #stack 8.4.4 osx"
  #   os: osx
install:
- mkdir -p ~/.local/bin
- export PATH="$HOME/.local/bin:$PATH"
- |
    if [ `uname` = "Darwin" ]
    then
      travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
- stack --version
- stack setup --no-terminal --install-cabal 2.2.0.1
- stack ghc -- --version
- stack build --only-dependencies --no-terminal
- stack clean
script:
- stack build --test :fbpmn-test --coverage --bench --no-run-benchmarks --no-terminal
  --ghc-options=-Werror
after_script:
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2
  | tar -xj
- "./shc fbpmn fbpmn-test"
notifications:
  email: false
before_deploy:
  - |
      if [ $TRAVIS_BRANCH = "develop" ]
      then
        export VERSION=$(${BINDIR}/fbpmn version)-SNAPSHOT
      else
        export VERSION=$(${BINDIR}/fbpmn version)
      fi
  - echo version is $VERSION
  - export ARCHIVE="${BINDIR}/fbpmn-${VERSION}-${OS}.${ARCH}"
  - echo archive basename is $ARCHIVE
  - tar czf "${ARCHIVE}.tar.gz" -C ${BINDIR} fbpmn
  - zip -j "${ARCHIVE}.zip" ${BINDIR}/fbpmn
  - export TRAVIS_TAG=v${VERSION}
  - |
      if [ $TRAVIS_BRANCH = "develop" ]
      then
        git tag ${TRAVIS_TAG}
        echo tag ${TRAVIS_TAG}
      else
        echo no tag
      fi
deploy:
  - provider: releases
    api_key:
      secure: aVme28spW6hNmDtHHQBuffcKNG7FRsN4Qa8GrRQzsIlTG9dIvnCMp64Wtz/PFr4Cm7NRgR3YshaL3GHQaxaGZLnJCmHRVrHQHa7oPd+mfo1/4Azzh73N91aIn6UqKr0Cd/nZtXa9+fDPD4UZARt8j3pkOf4e5ghwi3k6fQNAHdPIKlr+9o00BdursmlbU9E0Kwu7jNa1kPrxa/6XdFRLXRgsEqYARq2069OXXBU/tkfz6e4klAswR5ZxgoaqxhKjyZogDQOeffyGc1TR8TemmXDaOGknC0fc5+V7C7z4W7o/MWjARL3c8RTkkGFvQhTynJ55Txs88W3ueYa1AsN6UFJ5RYp6zD4KODYb0yU/g1RJ91On9YAcI+ObOpq6os7t5CAjgX2jw49/bfQwaPF/WTrY3sijjsG9VVBm86El8bTHO/qEu9rypgA2DHLFAl7Kzd/we2TBTjYSs9Dj6Zi0pSzyVmAJ8VaemmkAZEW8dDJBfnvoLvRsI+V5Rpk626qa/fF7gIJPpgMAYn32k07wVRgUK/ajoYqKQElTphoNpmq2tl9TctaRi8mj32UOf8P71ehQ2ZCSeagYXWjhhMxgVl8/j8TGxVu6SQNi8nzOM/wxtZQNS3jTtMiRz/ONF+3RS2nVi5EuX7pOGlEnXMvhNWQbd7xMZdWiTdes7a1lW9c=
    file:
      - ${ARCHIVE}.tar.gz
      - ${ARCHIVE}.zip
    skip_cleanup: true
    overwrite: true
    draft: false
    on:
      repo: pascalpoizat/fbpmn
      branch: master
      tags: true
    name: $TRAVIS_TAG
  - provider: releases
    api_key:
      secure: aVme28spW6hNmDtHHQBuffcKNG7FRsN4Qa8GrRQzsIlTG9dIvnCMp64Wtz/PFr4Cm7NRgR3YshaL3GHQaxaGZLnJCmHRVrHQHa7oPd+mfo1/4Azzh73N91aIn6UqKr0Cd/nZtXa9+fDPD4UZARt8j3pkOf4e5ghwi3k6fQNAHdPIKlr+9o00BdursmlbU9E0Kwu7jNa1kPrxa/6XdFRLXRgsEqYARq2069OXXBU/tkfz6e4klAswR5ZxgoaqxhKjyZogDQOeffyGc1TR8TemmXDaOGknC0fc5+V7C7z4W7o/MWjARL3c8RTkkGFvQhTynJ55Txs88W3ueYa1AsN6UFJ5RYp6zD4KODYb0yU/g1RJ91On9YAcI+ObOpq6os7t5CAjgX2jw49/bfQwaPF/WTrY3sijjsG9VVBm86El8bTHO/qEu9rypgA2DHLFAl7Kzd/we2TBTjYSs9Dj6Zi0pSzyVmAJ8VaemmkAZEW8dDJBfnvoLvRsI+V5Rpk626qa/fF7gIJPpgMAYn32k07wVRgUK/ajoYqKQElTphoNpmq2tl9TctaRi8mj32UOf8P71ehQ2ZCSeagYXWjhhMxgVl8/j8TGxVu6SQNi8nzOM/wxtZQNS3jTtMiRz/ONF+3RS2nVi5EuX7pOGlEnXMvhNWQbd7xMZdWiTdes7a1lW9c=
    file:
      - ${ARCHIVE}.tar.gz
      - ${ARCHIVE}.zip
    skip_cleanup: true
    overwrite: true
    draft: true
    on:
      repo: pascalpoizat/fbpmn
      branch: develop
      tags: false
    name: $TRAVIS_TAG
